using System.Collections.Immutable;
using System.Text;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp.Syntax;

namespace BuildingBlocks.Infrastructure.EfCore.Generator;

[Generator]
public sealed class ModuleDbContextFactoryGenerator : IIncrementalGenerator
{
    private const string ModuleDbContextMetadataName = "BuildingBlocks.Infrastructure.EfCore.ModuleDbContext";
    private const string NamingConventionsMetadataName = "Microsoft.EntityFrameworkCore.NamingConventionsOptionsExtensions";

    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        var classSymbols = context.SyntaxProvider
            .CreateSyntaxProvider(
                predicate: static (node, _) => node is ClassDeclarationSyntax { BaseList: not null },
                transform: static (ctx, ct) =>
                    ctx.SemanticModel.GetDeclaredSymbol((ClassDeclarationSyntax)ctx.Node, ct) as INamedTypeSymbol)
            .Where(static s => s is not null)
            .Select(static (s, _) => s!)
            .Collect();

        var compilationInfo = context.CompilationProvider
            .Select(static (c, _) => (
                BaseType: c.GetTypeByMetadataName(ModuleDbContextMetadataName),
                UseSnakeCase: c.GetTypeByMetadataName(NamingConventionsMetadataName) is not null));

        context.RegisterSourceOutput(
            classSymbols.Combine(compilationInfo),
            static (ctx, pair) =>
            {
                var (symbols, (baseType, useSnakeCase)) = pair;
                if (baseType is null)
                    return;

                foreach (var symbol in symbols)
                {
                    if (!symbol.IsAbstract && InheritsFrom(symbol, baseType))
                        ctx.AddSource($"{symbol.Name}Factory.g.cs", GenerateSource(symbol, useSnakeCase));
                }
            });
    }

    private static bool InheritsFrom(INamedTypeSymbol symbol, INamedTypeSymbol targetBase)
    {
        var current = symbol.BaseType;
        while (current is not null)
        {
            if (SymbolEqualityComparer.Default.Equals(current, targetBase))
                return true;
            current = current.BaseType;
        }
        return false;
    }

    private static string GenerateSource(INamedTypeSymbol symbol, bool useSnakeCase)
    {
        var name = symbol.Name;
        var ns = symbol.ContainingNamespace is { IsGlobalNamespace: false } containingNs
            ? containingNs.ToDisplayString()
            : null;

        var sb = new StringBuilder();
        sb.AppendLine("// <auto-generated/>");
        sb.AppendLine("using Microsoft.EntityFrameworkCore;");
        sb.AppendLine("using Microsoft.EntityFrameworkCore.Design;");
        sb.AppendLine();

        if (ns is not null)
        {
            sb.AppendLine($"namespace {ns};");
            sb.AppendLine();
        }

        sb.AppendLine($"internal sealed class {name}Factory : IDesignTimeDbContextFactory<{name}>");
        sb.AppendLine("{");
        sb.AppendLine($"    public {name} CreateDbContext(string[] args) =>");
        sb.AppendLine($"        new(new DbContextOptionsBuilder<{name}>()");
        sb.AppendLine("            .UseNpgsql()");
        if (useSnakeCase)
            sb.AppendLine("            .UseSnakeCaseNamingConvention()");
        sb.AppendLine("            .Options);");
        sb.AppendLine("}");

        return sb.ToString();
    }
}
