// <auto-generated />
using System;
using Gloss.Infrastructure;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Gloss.Infrastructure.Migrations
{
    [DbContext(typeof(GlossDbContext))]
    [Migration("20260404170000_AddMrDiffShas")]
    partial class AddMrDiffShas
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Gloss.Domain.Configs.Config", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("DefaultPollCron")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("GitBaseUrl")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string[]>("GitProjects")
                        .IsRequired()
                        .HasColumnType("text[]");

                    b.Property<string>("GitProvider")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("GitToken")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("LlmApiKey")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("LlmMaxTokens")
                        .HasColumnType("integer");

                    b.Property<string>("LlmModel")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("LlmProvider")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("LlmReasoningEnabled")
                        .HasColumnType("boolean");

                    b.Property<int>("LlmThinkingBudget")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("configs", (string)null);
                });

            modelBuilder.Entity("Gloss.Domain.MergeRequests.DraftComment", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Body")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("FilePath")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Line")
                        .HasColumnType("integer");

                    b.Property<Guid>("MergeRequestId")
                        .HasColumnType("uuid");

                    b.Property<string>("Reasoning")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("MergeRequestId");

                    b.ToTable("draft_comments", (string)null);
                });

            modelBuilder.Entity("Gloss.Domain.MergeRequests.MergeRequest", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("AuthorUsername")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("BaseSha")
                        .HasColumnType("text");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<string>("Diff")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("HeadSha")
                        .HasColumnType("text");

                    b.Property<int>("ProviderIid")
                        .HasColumnType("integer");

                    b.Property<Guid>("RepositoryId")
                        .HasColumnType("uuid");

                    b.Property<int>("State")
                        .HasColumnType("integer");

                    b.Property<string>("SourceBranch")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("StartSha")
                        .HasColumnType("text");

                    b.Property<string>("TargetBranch")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("RepositoryId", "ProviderIid")
                        .IsUnique();

                    b.ToTable("merge_requests", (string)null);
                });

            modelBuilder.Entity("Gloss.Domain.Repositories.Repository", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("PollCron")
                        .HasColumnType("text");

                    b.Property<string>("ProjectPath")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Provider")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("repositories", (string)null);
                });

            modelBuilder.Entity("Gloss.Domain.MergeRequests.DraftComment", b =>
                {
                    b.HasOne("Gloss.Domain.MergeRequests.MergeRequest", null)
                        .WithMany()
                        .HasForeignKey("MergeRequestId")
                        .HasConstraintName("FK_draft_comments_merge_requests_MergeRequestId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Gloss.Domain.MergeRequests.MergeRequest", b =>
                {
                    b.HasOne("Gloss.Domain.Repositories.Repository", null)
                        .WithMany()
                        .HasForeignKey("RepositoryId")
                        .HasConstraintName("FK_merge_requests_repositories_RepositoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
