// <auto-generated />
using System;
using Gloss.Infrastructure;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Gloss.Infrastructure.Migrations
{
    [DbContext(typeof(GlossDbContext))]
    [Migration("20260404111510_AddConfigsTable")]
    partial class AddConfigsTable
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Gloss.Domain.Configs.Config", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("DefaultPollCron")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("GitBaseUrl")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string[]>("GitProjects")
                        .IsRequired()
                        .HasColumnType("text[]");

                    b.Property<string>("GitProvider")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("GitToken")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("LlmApiKey")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("LlmModel")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("LlmProvider")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("LlmReasoningEnabled")
                        .HasColumnType("boolean");

                    b.HasKey("Id");

                    b.ToTable("configs", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
